objetivos/README.md
#Entrega del hito de Cloud Computing
##Enlace a fichero de objetivos
##Lista de comprobación
=> Arreglando upstream de objetivos/README.md

objetivos/PabloMartín-MorenoRuiz.md
#Entrega del hito de Cloud Computing
##Enlace a fichero de objetivos
##Lista de comprobación
=> Entregando objetivos

objetivos/FranciscoJavierBolivarLupianez.md
#Entrega del hito de Cloud Computing
##Enlace a fichero de objetivos
##Lista de comprobación
=> Objetivos primera semana

objetivos/JoséLuisFernandezAguilera.md, proyecto/0.md
Corresponde al hito 0 y entrega de fichero de objetivos 
[Enlace](https://github.com/okynos/CC16-17/blob/master/objetivos/Jos%C3%A9LuisFernandezAguilera.md)
Se ha entregado la lista de objetivos completa junto con la modificación de la lista para añadir el hito 0
[Hito 0](https://github.com/okynos/ProyectoCC/milestone/1)
[Issue 1 - Pull Request](https://github.com/okynos/ProyectoCC/issues/1)
[Issue 2 - Creación del proyecto](https://github.com/okynos/ProyectoCC/issues/2)
[Issue 3 - Documentación con GH Pages](https://github.com/okynos/ProyectoCC/issues/3)
=> Pull request del hito 0 revisado y todo correcto.

proyecto/0.md
Corresponde al [hito 0](https://github.com/fblupi/master_informatica-CC/milestone/1)
Entrega del [hito 0](https://github.com/fblupi/master_informatica-CC/milestone/1)
Completado [hito 0](https://github.com/fblupi/master_informatica-CC/milestone/1)
=> Enlace a proyecto y documentación

objetivos/ManuelBlancoRienda.md, proyecto/0.md
https://github.com/manuelbr/CC16-17/blob/master/objetivos/ManuelBlancoRienda.md
Se entrega tanto la tabla actualizada de los proyectos de los alumnos (con mis datos correspondientes) como mi fichero de objetivos. Se ha actualizado correctamente el repositorio sin conflictos.
https://github.com/manuelbr/Proyecto_CC/issues?q=is%3Aissue+is%3Aclosed
(En el enlace están todos los issues correspondientes a este hito 0, así como su descripción)
=> Entrega de hito 0 por parte de Manuel Blanco Rienda

objetivos/MarvinMatiasAgueroTorales.md, proyecto/0.md
[Objetivos](https://github.com/JJ/CC16-17/blob/master/objetivos/MarvinMatiasAgueroTorales.md)
Se crea un fichero con mi nombre completo, y se agregan los objetivos del hito en el mismo. Se modifica el fichero correspondiente al fichero de entrega del proyecto de la asignatura.
[Issue 1](https://github.com/mmaguero/MII-CC16-17/issues/1)
[Hito 0](https://github.com/mmaguero/MII-CC16-17/milestone/1?closed=1)
Mis commits [1](https://github.com/mmaguero/MII-CC16-17/commits/master) y [2](https://github.com/mmaguero/MII-CC16-17/commits/gh-pages)
=> Agrego mis objetivos y agrego mi proyecto (sin isuess aquí)

objetivos/JoseManuelMoyaBaena.md, proyecto/0.md
https://github.com/jose999/CC16-17/blob/master/objetivos/JoseManuelMoyaBaena.md
Entrega del hito 0
Hito 0
=> Añadido Objetivos e informacion del proyecto

objetivos/PorcelPorcelJuanPablo.md, proyecto/0.md
Corresponde al hito 0 y entrega de fichero de objetivos 
[Fichero de objetivos](https://github.com/JPPorcel/CC16-17/blob/master/objetivos/PorcelPorcelJuanPablo.md)
Completado y subido el fichero con la lista de objetivos para la primera semana y añadida la línea de mi proyecto en la lista de proyectos.
[Hito 0](https://github.com/JPPorcel/CC-Project/milestone/1)
[Issue 1 - Creación del repositorio con licencia y readme.](https://github.com/JPPorcel/CC-Project/issues/1)
[Isuue 2 - Crear página con gh-pages.](https://github.com/JPPorcel/CC-Project/issues/2)
=> Archivo de objetivos completado y enlace a proyecto y documentación

objetivos/MichaelGoldsmith.md, proyecto/0.md
[enlace a los objetivos correspondientes a este hito](https://github.com/goldy1992/CC16-17/blob/master/objetivos/MichaelGoldsmith.md "objetivos")
He subido los ficheros del objetivos al repositorio como es pedido en el hito0
=> Michael Goldsmith hito 0 Corregido

objetivos/MarioOrtegaAguayo.md, proyecto/0.md
https://github.com/mortega87/CC16-17/blob/master/objetivos/MarioOrtegaAguayo.md
* [X ] He actualizado con la última versión del fichero de entrega y
Entregado fichero objetivos e hito 0
Hito 0
=> Entregado fichero objetivos e hito 0

objetivos/DanielPerezGazquez.md, proyecto/0.md
Corresponde al hito 0 y entrega de fichero de objetivos 
https://github.com/NestorsImagination/CC16-17/blob/master/objetivos/DanielPerezGazquez.md
Objetivos + enlaces añadidos a 0.md
https://github.com/NestorsImagination/CC-Project/milestone/1
https://github.com/NestorsImagination/CC-Project/issues/1
https://github.com/NestorsImagination/CC-Project/issues/2
=> Hito 0 Daniel Pérez Gázquez

objetivos/GustavoRivasGervilla.md, proyecto/0.md
Corresponde al hito 0 y fichero de objetivos
https://github.com/JJ/CC16-17/blob/master/sesiones/1-semana.md
##Lista de comprobación para hitos
Adjunto el fichero de objetivos con los objetivos cumplidos para de la primera semana, con alguna información adicional que ayude a corroborar que se han alcanzado dichos objetivos. También modifico la tabla de proyectos con la información sobre el mío.
https://github.com/Griger/CC/milestone/1, no se han añadido issues con respecto a la generación de la web por descuido del alumno.
=> Añadir fichero de objetivos Gustavo Rivas Gervilla y entrega hito 0

objetivos/PabloVilchezGarcia.md, proyecto/0.md
Corresponde al hito 0 y entrega de fichero objetivos
[Objetivos](https://github.com/pablovilchezg/CC16-17/blob/master/objetivos/PabloVilchezGarcia.md)
Entregado el hito 0, modificada la lista y fichero objetivos
[Closed Issues](https://github.com/pablovilchezg/cloud-computing-project/issues?q=is%3Aissue+is%3Aclosed)
=> Fichero objetivos y modificacion de 0.md con datos del proyecto

objetivos/JesusChecaHidalgo.md, proyecto/0.md
[Objetivos](https://github.com/JeMaCheHi/CC16-17/blob/master/objetivos/JesusChecaHidalgo.md)
Alcanzado el hito 0, consistente en la creación del repo del proyecto, configuración de éste, y adición del fichero de objetivos al repo común de la asignatura.
[Issues](https://github.com/JeMaCheHi/ProyectoCC16-17/issues?q=is%3Aissue+is%3Aclosed)
[Hito0](https://github.com/JeMaCheHi/ProyectoCC16-17/milestone/1?closed=1)
=> Añadido fichero de objetivos y modificado 0.md con datos de proyecto

proyecto/0.md
He actualizado el enlace del fichero0.md del proyecto para que contenga el enlace correcto a gh-pages donde realizaré la documentación y ejercicios de la asignatura.
=> modificando enlace de documentacion para que apunte a gh-pages

objetivos/JesúsGarcíaManday.md, proyecto/0.md
=> Entrega del fichero objetivos y del hito 0

objetivos/JuanPabloGonzalezCasado.md, proyecto/0.md
y
https://github.com/Pablo126/CC16-17/blob/master/objetivos/JuanPabloGonzalezCasado.md
Objetivos y ficheros del repositorio
[hito0](https://github.com/Pablo126/Cloud-Computing-1617/milestone/1)
=> Objetivos y enlaces proyecto

objetivos/AythamiEstevezOlivas.md, proyecto/0.md
Corresponde al hito 0 y entrega de fichero de objetivos 
[Objetivos](https://github.com/AythaE/CC16-17/blob/master/objetivos/AythamiEstevezOlivas.md)
Entrega del hito 0 tras diversos problemas por un commit pasado con el correo mal configurado
[Hito 0](https://github.com/AythaE/Proyecto_CC16-17/milestone/1)
[Issue](https://github.com/AythaE/Proyecto_CC16-17/issues/1)
=> Añadido fichero de objetivos e hito 0

objetivos/JavierAlvarezCastillo.md, proyecto/0.md
o
https://github.com/JavierAlvarezCastillo/CC16-17/blob/master/objetivos/JavierAlvarezCastillo.md
Entrega del hito 0 que contiene el milestone que he creado para el hito 0, así como los dos issues que he creado para el milestone. También se ha entregado el fichero de objetivos.
https://github.com/JavierAlvarezCastillo/CloudComputing-Proyecto/milestone/1
https://github.com/JavierAlvarezCastillo/CloudComputing-Proyecto/issues/1
https://github.com/JavierAlvarezCastillo/CloudComputing-Proyecto/issues/2
=> hito 0 y objetivos

proyecto/0.md
Entrega del hito 0 con la dirección del repositorio de mi proyecto
https://github.com/pmmre/ProyectoCC16-17/milestone/1
https://github.com/pmmre/ProyectoCC16-17/issues/1
https://github.com/pmmre/ProyectoCC16-17/issues/2
https://github.com/pmmre/ProyectoCC16-17/issues/3
https://github.com/pmmre/ProyectoCC16-17/issues/4
=> Subiendo hito 0 con repositorio del proyecto

objetivos/MariaVictoriaSantiagoAlcala.md, proyecto/0.md
Corresponde al hito 0 y entrega del fichero de objetivos 
[Fichero de objetivos] (https://github.com/STiago/CC16-17/blob/master/objetivos/MariaVictoriaSantiagoAlcala.md)
Entrega de la tabla actualizada de los proyectos de los alumnos donde he introducido mis datos y entrega de mi fichero de objetivos.
[Hito 0] (https://github.com/STiago/CC_Project/milestones)
[Issues] (https://github.com/STiago/CC_Project/issues?q=is%3Aissue+is%3Aclosed)
=> Entrega del hito 0 y fichero de objetivos

proyecto/0.md
Corresponde a la corrección del hito 0.
[Enlace](https://github.com/AythaE/CC16-17/blob/master/objetivos/AythamiEstevezOlivas.md).
Corrección del hito 0 aplicando la corrección de dicho hito.
[Hito 0](https://github.com/AythaE/Proyecto_CC16-17/milestone/1)
[Issue 1](https://github.com/AythaE/Proyecto_CC16-17/issues/1)
[Issue 2](https://github.com/AythaE/Proyecto_CC16-17/issues/2)
[Issue 3](https://github.com/AythaE/Proyecto_CC16-17/issues/3)
=> Añadidas correccion del hito 0

proyecto/0.md
Para mejorar la nota del Hito 0 he creado un nuevo repo, organizando correctamente los ficheros del repositorio del proyecto, he cambiado la rama para la web git (gh-pages) y cerrado los issues desde commit.
https://github.com/mortega87/ProyectoCC-16-17/
https://github.com/mortega87/ProyectoCC-16-17/issues/2
https://github.com/mortega87/ProyectoCC-16-17/issues/1
=> Mejora de Repositorio para proyecto e Issues desde commit

proyecto/0.md
Se ha corregido el error del hito 0 en el cual los commits no cerraban el issue o si lo cerraban no hacían una buena referencia al issue.
[Issue 4](https://github.com/okynos/ProyectoCC/issues/4)
[Milestone 0](https://github.com/okynos/ProyectoCC/milestones)
=> Corregidos los issues y cerrados.

proyecto/0.md
Actualización y corrección del Hito 0.
[Hito 0](https://github.com/jmanday/ProyectoCC16-17/milestone/2)
=> Corrigiendo Hito 0

objetivos/JoseAngelDiazGarcia.md, proyecto/0.md
Corresponde al hito 0 y la entrega de fichero de objetivos 
[Objetivos Jose Angel Diaz](https://github.com/joseangeldiazg/CC16-17/blob/commitsJADG/objetivos/JoseAngelDiazGarcia.md)
En este primer Pull Request se entrega el fichero de objetivos y los enlaces al repositorio final creado para superar el hito 0 del proyecto de la asignatura. 
Una vez creado el repositorio los issues de este primer hito 0 han sido dos: 
[Creación de la página del proyecto usando Github Pages](https://github.com/joseangeldiazg/MII-CloudComputing/issues/1)
[Adecuación de los repositorios](https://github.com/joseangeldiazg/MII-CloudComputing/issues/2)
=> Objetivos e hito 0.

objetivos/AlejandroCasadoQuijada.md
[Objetivos](https://github.com/acasadoquijada/CC16-17/blob/master/objetivos/AlejandroCasadoQuijada.md)
=> Entrega objetivos sesiones 2 y 3

objetivos/JuanFranciscoRodriguezVilchez.md
https://github.com/juanfranrv/CC16-17/blob/master/objetivos/JuanFranciscoRodriguezVilchez.md
Entrega objetivos
=> Actualizando objetivos de las últimas semanas closes #8

objetivos/HugoBarzanoCruz.md
#Entrega de fichero de objetivos 
[Objetivos](https://github.com/hugobarzano/CC16-17/blob/master/objetivos/HugoBarzanoCruz.md)
* [X ] He llevado a cabo las actividades correspondientes al objetivo y he entendido para qué sirve.  
Entrega de los objetivos correspondientes a la sesion 2 y 3 junto con los ejercicios del tema 1
[Milestone ejercicios Tema 1](https://github.com/hugobarzano/ProyectoCC16-17/milestone/2)
=> objetivos sesion 2 y sesion 3

objetivos/PedroGazquezNavarrete.md
o
[Borrar lo que no corresponda]
[[ Y lo de arriba también ]]
=> Actualizando objetivos

objetivos/PedroGazquezNavarrete.md
https://github.com/JJ/CC16-17/blob/master/objetivos/PedroGazquezNavarrete.md
Entrega de los correspondientes objetivos de las semanas 2 y 3.
=> Arreglando fichero objetivos

objetivos/CesarAlbusacJorge.md
Objetivos: https://github.com/JJ/CC16-17/blob/master/objetivos/CesarAlbusacJorge.md
* [x ] He llevado a cabo las actividades correspondientes al objetivo y he entendido para qué sirve.
* [x ] He actualizado con la última versión del fichero de entrega y
Actualizando objetivos de la semana 2 y 3.
Ejercicios: https://github.com/cesar2/CloudComputing1617/blob/master/Ejercicios/EjerciciosTema1.md
=> Objetivos semana 2 y 3

objetivos/ManuelBlancoRienda.md
Entrega de fichero de objetivos de Manuel Blanco Rienda
[Enlace](https://github.com/manuelbr/CC16-17/blob/master/objetivos/ManuelBlancoRienda.md)
Se han actualizado los objetivos de la segunda y tercera semana de Manuel Blanco Rienda.
=> Actualización de los objetivos de la segunda y tercera semana de Manuel Blanco Rienda

objetivos/JoseAngelDiazGarcia.md
#Entrega de fichero de objetivos 
En esta entrega he añadido la actualización de los objetivos cumplidos en la semana 2 y 3 de clases de la asignatura Cloud Computing, aunque aún quedan algunos por completar sobre tecnologías a usar ya que aun no lo tengo muy claro. 
[Enlace a objetivos](https://github.com/joseangeldiazg/CC16-17/blob/commitsJADG/objetivos/JoseAngelDiazGarcia.md)
También se ha añadido los ejercicios del tema sobre arquitectura software. [Enlace a ejercicios](https://github.com/joseangeldiazg/MII-CloudComputing-Ejercicios/blob/master/T1/ejerciciosT1-CC.md)
=> Actualización de objetivos y entrega ejercicios T1.

objetivos/FranciscoJavierBolivarLupianez.md, proyecto/0.md
https://github.com/fblupi/CC16-17/blob/master/objetivos/FranciscoJavierBolivarLupianez.md
Entregados los objetivos de la segunda semana y cambiado el repo del proyecto
=> Objetivos segunda semana y migración de repo del proyecto

objetivos/ManuelBlancoRienda.md, proyecto/1.md
https://github.com/manuelbr/CC16-17/blob/master/objetivos/ManuelBlancoRienda.md
Entrega del hito 1, en el que se ha creado un nuevo fichero de entrega para el citado hito, habiendo
rellenado los datos correspondientes a mi proyecto. Se han trasladado los ejercicios de este tema
a un nuevo repositorio, se ha añadido cierta documentación inicial del proyecto, además de haber actualizado el fichero README con la arquitectura que usará el software y una descripción inicial del mismo.
https://github.com/manuelbr/Proyecto_CC/issues/4
https://github.com/manuelbr/Proyecto_CC/issues/5
https://github.com/manuelbr/Proyecto_CC/issues/6
https://github.com/manuelbr/Proyecto_CC/issues/7 …
=> Entrega del hito 1

objetivos/JesusGarciaManday.md, proyecto/0.md, proyecto/1.md
Entrega del hito 1 y objetivos de la cuarta semana
[Milestone Hito 1](https://github.com/jmanday/CRUT/milestone/1)
=> Entrega del hito 1 y fichero objetivos de la cuarta semana

objetivos/AlejandroCasadoQuijada.md, proyecto/0.md, proyecto/1.md
Los objetivos se pueden consultar [aquí](https://github.com/acasadoquijada/CC16-17/blob/master/objetivos/AlejandroCasadoQuijada.md)
Esta entrega se corresponde con el hito número 1 de la asignatura que trata sobre la arquitectura del proyecto
* https://github.com/acasadoquijada/MyStudentBot/milestone/1?closed=1
* https://github.com/acasadoquijada/MyStudentBot/issues/6
* https://github.com/acasadoquijada/MyStudentBot/issues/1
=> Entrega hito 1 y objetivos

objetivos/HugoBarzanoCruz.md, proyecto/1.md
[Objetivos](https://github.com/hugobarzano/CC16-17/blob/master/objetivos/HugoBarzanoCruz.md)
Entrega correspondiente al hito 1 donde se describe el proyecto a realizar en la asignatura, así como su arquitectura. 
[Milestone Hito 1](https://github.com/hugobarzano/OpenFractal/milestone/4?closed=1)
=> Entrega Hito 1

proyecto/1.md
Se entrega el hito 1, en el que he decidido realizar un BOT de Telegram para obtener chistes de distintas categorías.
Enlace al Hito 1 de mi repositorio:
https://pedrogazquez.github.io/FunnyBot/
=> Añadiendo hito 1 a 1.md

objetivos/PorcelPorcelJuanPablo.md, proyecto/1.md
Corresponde al hito 1 y entrega de fichero de objetivos
[Fichero de objetivos](https://github.com/JPPorcel/CC16-17/blob/master/objetivos/PorcelPorcelJuanPablo.md)
Entrega del hito 1 y ejercicios del Tema 1 sobre Arquitectura software en la nube. En esta entrega se especifica la arquitectura que se va a desarrollar para el proyecto de la asignatura.
* [Hito 1](https://github.com/JPPorcel/Proyecto-Elliot/milestone/2)
* [Actualizar Readme con licencia y descripción del proyecto](https://github.com/JPPorcel/Proyecto-Elliot/issues/4)
* [Añadir documentación a gh-pages](https://github.com/JPPorcel/Proyecto-Elliot/issues/5)
* [Ejercicio 1 - Tema …
=> Añadiendo objetivos y enlaces proyecto

objetivos/JoseManuelMoyaBaena.md, proyecto/1.md
Corresponde al hito 1 y Entrega de fichero de objetivos semana 2,3,4
https://github.com/jose999/CC16-17/blob/master/objetivos/JoseManuelMoyaBaena.md
Actualizacion del archivo objetivos, entrega del hito 1 y actualizacion con la explicacion del proyecto del gh-pages
https://jose999.github.io/ProyectoCC2016/
=> Añadidos objetivos semana 2,3,4 y entrega Hito 1

proyecto/1.md
https://github.com/JJ/CC16-17/blob/master/objetivos/PabloMart%C3%ADn-MorenoRuiz.md
Entrega de la descripción del proyecto recogida en el hito 1 de la asignatura
https://github.com/pmmre/CineForYou/milestone/2
=> Subiendo hito 1

objetivos/PerezGazquezDaniel.md, proyecto/1.md
o
[Borrar lo que no corresponda]
[[ Y lo de arriba también ]]
=> Hito 1 Daniel Pérez Gázquez

objetivos/MarvinMatiasAgueroTorales.md, proyecto/1.md
y
https://github.com/JJ/CC16-17/blob/master/objetivos/MarvinMatiasAgueroTorales.md
* [x ] He leído el guión del hito
* [x ] Cumplo los prerrequisitos
* [x ] He actualizado con la última versión del fichero de entrega y
* [x ] He llevado a cabo las actividades correspondientes al objetivo y he entendido para qué sirve.
* [x ] He actualizado con la última versión del fichero de entrega y
Objetivos, Hito1, Ejercicios propuestos de arquitectura de software (https://github.com/mmaguero/Ejercicios-CC16-17-MII/tree/master/ArquitecturaSoftware)
https://github.com/mmaguero/MII-CC16-17/issues/2 …
=> Agregando objetivos y line de proyecto. References #2

objetivos/GustavoRivasGervilla.md, proyecto/1.md
o
https://github.com/JJ/CC16-17/blob/master/objetivos/GustavoRivasGervilla.md
Se resube la documentación relativa al Hito 1, anteriormente se había modificado una linea vacía debajo de la línea de Victoria, así que ahora he añadido la línea al final del documento.
https://github.com/Griger/CC/milestone/2
=> Resubir hito1

objetivos/MarioOrtegaAguayo.md, proyecto/1.md
Corresponde al hito 1 y Entrega de fichero de objetivos 
https://github.com/mortega87/CC16-17/blob/master/objetivos/MarioOrtegaAguayo.md
Entrega Hito 1 y actualización objetivos
https://github.com/mortega87/ProyectoCC-16-17/issues/4
https://github.com/mortega87/ProyectoCC-16-17/issues/3
=> Entrega Hito 1 y actualización objetivos

proyecto/1.md
https://github.com/mortega87/CC16-17/blob/master/objetivos/MarioOrtegaAguayo.md
He añadido la descripción del proyecto al README como indicó en la corrección.
https://github.com/mortega87/ProyectoCC-16-17/issues/5
=> Corrección - Añadido README de proyecto

proyecto/1.md
[Hito 1](https://github.com/jmanday/CRUT/milestone/1)
[Objetivos](https://github.com/JJ/CC16-17/blob/master/objetivos/JesusGarciaManday.md)
Entrega del hito 1
[Hito 1](https://github.com/jmanday/CRUT/milestone/1)
=> Añadida descripción al fichero README

proyecto/1.md
Corrección del hito 1: La descripción del proyecto esta en el [README de la rama master](https://github.com/hugobarzano/OpenFractal/blob/master/README.md)
[Milestone para correcciones](https://github.com/hugobarzano/OpenFractal/milestone/5?closed=1)
=> Corrigiendo hito 1

proyecto/1.md
* [x ] He leído el guión del hito
Entrega del hito 1 de cloud computing. En este hito se ha especificado la arquitectura a usar así como las tecnologías. 
[Issue: Hito 1](https://github.com/joseangeldiazg/MII-CloudComputing/issues/3)
=> Entrega del hito 1.

proyecto/1.md
https://github.com/manuelbr/CC16-17/blob/master/objetivos/ManuelBlancoRienda.md
Modificación del hito 1, añadiendo la actualización que se ha realizado en el fichero del correspondiente hito: Se ha cambiado la arquitectura que se usará durante el proyecto y se han añadido la definición de los componentes que tendrá dicha arquitectura.
https://github.com/manuelbr/Proyecto_CC/issues/12 (Issue de modificación del archivo)
En la primera entrega del hito uno se encuentran el resto de issues que se utilizaron.
a día 1/11/2016
=> modificación de archivo del hito 1, con la actualización realizada a la documentación de mi proyecto.

proyecto/1.md
Corrección del hito 1: descripción del proyecto en el README de la rama master
[Documentación en README.md de master](https://github.com/fblupi/GEventator/issues/9)
=> Corrección hito 1

proyecto/1.md
Corrección del hito 1. Se ha añadido la documentación en el README de la rama master.
[Issue 8. Añadir documentacion](https://github.com/acasadoquijada/MyStudentBot/issues/8)
=> Correcion hito 1

proyecto/1.md
Corrección del hito 1. Se han especificado los distintos microservicios en el readme del proyecto
[Corrección Hito 1](https://github.com/JPPorcel/Proyecto-Elliot/issues/6)
=> Actualización tabla hito 1 con enlace a issue

proyecto/1.md
Se corrige el hito 1: cambiando la documentación/descripción del proyecto al fichero README del proyecto y quitando la estructura en hitos de la web del proyecto.
[issue creado](https://github.com/Griger/CC/issues/6)
=> Corrigiendo Hito1: estructura documentación

objetivos/MichaelGoldsmith.md
[objetivos](https://github.com/goldy1992/CC16-17/blob/master/objetivos/MichaelGoldsmith.md)
[hito 1](https://goldy1992.github.io/proyecto-cloud-computing-16-17/)
La entrega del hito 1
=> He vuelto a hacer un pull request

objetivos/JoseAngelDiazGarcia.md
#Entrega de fichero de objetivos 
##Enlace a fichero de objetivos
[Objetivos](https://github.com/joseangeldiazg/CC16-17/blob/commitsJADG/objetivos/JoseAngelDiazGarcia.md).
Actualización de los objetivos cumplidos de la semana 4 y 3. Actualización del enlace al hito 1.
=> Actualización de objetivos semana 4.

proyecto/1.md
he puesto mi nombre y el proyecto en 1.md
=> puse mi nombre en 1.md

objetivos/JuanPabloGonzalezCasado.md, proyecto/1.md
[Objetivos hito 1](https://github.com/Pablo126/CC16-17/blob/master/objetivos/JuanPabloGonzalezCasado.md)
Ejercicios tema 1 y hito 1 del proyecto con descripción del proyecto a realizar.
https://github.com/Pablo126/Cloud-Computing-1617/issues/3
https://github.com/Pablo126/Cloud-computing-Ejercicios/issues/1
=> Entrega de hito1 Juan Pablo González

sesiones/2-semana.md, sesiones/3-semana.md, sesiones/4-semana.md, sesiones/5-semana.md, sesiones/6-semana.md
**Explicación del Pull Request:**
Corrección de los enlaces para apuntarse al [Certamen de proyectos de software libre de la UGR](http://osl.ugr.es/2016/09/30/tercera-edicion-del-certamen-de-proyectos-libres-de-la-ugr/). Los enlaces anteriores apuntaban a la encuesta inicial de la asignatura.
=> Corrección enlaces apuntarse certamen proyectos.

sesiones/6-semana.md
**Descripción pull request:**
Corregido enlace al hito 2 de la sexta semana
=> Corregido enlace Hito 2

objetivos/PedroGazquezNavarrete.md
https://github.com/JJ/CC16-17/blob/master/objetivos/PedroGazquezNavarrete.md
* [x ] He llevado a cabo las actividades correspondientes al objetivo y he entendido para qué sirve.
* [x ] He actualizado con la última versión del fichero de entrega y añadido mi contribución en una línea que no cree conflictos
=> Arreglando objetivos

objetivos/JoseLuisFernandezAguilera.md, proyecto/2.md
y
[Objetivos](https://github.com/JJ/CC16-17/blob/master/objetivos/JoseLuisFernandezAguilera.md)
En este pull se entrega todo lo referente al hito 2 incluyendo tutoriales de provisionamiento en varios lenguajes, prueba de los mismos con un compañero y la documentación asociada, también se entregan los ejercicios referentes a este tema.
[Hito 2](https://github.com/okynos/ProyectoCC/milestone/3)
[Issue 8](https://github.com/okynos/ProyectoCC/issues/8)
[Issue 9](https://github.com/okynos/ProyectoCC/issues/9)
[Issue 10](https://github.com/okynos/ProyectoCC/issues/10)
[Issue 11](https://github.com/okynos/ProyectoCC/issues/11)
[Issue 12 pull request](https://github.com/okynos/ProyectoCC/pull/12)
[Issue …
=> Añadido fichero de entrega del hito 2 y objetivos.

objetivos/ManuelBlancoRienda.md, proyecto/2.md
https://github.com/manuelbr/CC16-17/blob/master/objetivos/ManuelBlancoRienda.md
Entrega del hito 2, con los objetivos que incluyen la realización de 4 de los 6 ejercicios del tema y en enlace al fichero donde se muestra la correción hecha al compañero José Luis Fernández Aguilera, además de la inclusión de la guía de provisionamiento correspondiente con ansible y el script desarrollado para tal objetivo.
[Enlace a ejercicios del tema 2](https://github.com/manuelbr/ejercicios_CC/tree/master/tema_2)
https://github.com/manuelbr/Proyecto_CC/issues/32
https://github.com/manuelbr/Proyecto_CC/issues/31
https://github.com/manuelbr/Proyecto_CC/issues/29 …
=> Entrega del hito 2 de Manuel Blanco Rienda

objetivos/PorcelPorcelJuanPablo.md, proyecto/2.md
Corresponde al hito 2 y entrega de fichero de objetivos
[Fichero de objetivos](https://github.com/JPPorcel/CC16-17/blob/master/objetivos/PorcelPorcelJuanPablo.md)
Entrega del hito 2 y ejercicios del Tema 2 sobre Gestión de infraestructuras virtuales.
* [Hito 2](https://github.com/JPPorcel/Proyecto-Elliot/milestone/3)
* [Provisionamiento con Ansible y Chef](https://github.com/JPPorcel/Proyecto-Elliot/issues/7)
* [Añadir provisionamiento a rama de documentación ](https://github.com/JPPorcel/Proyecto-Elliot/issues/8)
* [Ejercicios Tema 2](https://github.com/JPPorcel/CC-Ejercicios/milestone/2)
=> Entrega hito 2 Juan Pablo Porcel

objetivos/MichaelGoldsmith.md, proyecto/2.md
https://github.com/goldy1992/CC16-17/blob/master/objetivos/MichaelGoldsmith.md
el enlace con toda la materia de este hito
=> la entrega de hito 2

objetivos/PerezGazquezDaniel.md, proyecto/2.md
[Fichero de objetivos](https://github.com/NestorsImagination/CC16-17/blob/master/objetivos/PerezGazquezDaniel.md)
* [ x] He leído el guión del hito
* [x ] Cumplo los prerrequisitos
* [x ] He actualizado con la última versión del fichero de entrega y
* [ x] He llevado a cabo las actividades correspondientes al objetivo y he entendido para qué sirve.
* [ x] He actualizado con la última versión del fichero de entrega y
Hito 2 y ejercicios correspondientes al tema de Provisionamiento de Máquinas Virtuales
##Issues cerrados
[Issues cerrados (desde el 11 al 16)](https://github.com/NestorsImagination/Sample-Multiplayer-Shooter/issues?q=is%3Aissue+is%3Aclosed)
* [Enlace a los …
=> Entrega Hito 2 Daniel Pérez Gázquez

objetivos/JesusGarciaManday.md, proyecto/2.md
Hito 2
[Objetivos](https://github.com/JJ/CC16-17/blob/master/objetivos/JesusGarciaManday.md)
Entrega de los enlaces para el hito 2
[Hito 2](https://github.com/jmanday/CRUT/milestone/2?closed=1)
=> Añadidos los enlaces para el hito 2

objetivos/AythamiEstevezOlivas.md, proyecto/2.md
Corresponde al hito 2 y Entrega de fichero de objetivos hasta la octava semana
[Enlace](https://github.com/AythaE/CC16-17/blob/master/objetivos/AythamiEstevezOlivas.md)
Entrega del hito 2, los ejercicios del tema 2 y los objetivos hasta la octava semanma
[Hito 2](https://github.com/AythaE/DeFesti/milestone/3)
[Issue 8](https://github.com/AythaE/DeFesti/issues/8)
[Issue 9](https://github.com/AythaE/DeFesti/issues/9)
[Issue 10](https://github.com/AythaE/DeFesti/issues/10)
[Hito ejercicios tema 2](https://github.com/AythaE/Ejercicios-CC16-17/milestone/3)
[Directorio ejercicios tema 2](https://github.com/AythaE/Ejercicios-CC16-17/tree/master/Gestion_de_configuraciones)
=> Añadido hito 2 y objetivos hasta la semana 8

objetivos/PedroGazquezNavarrete.md, proyecto/2.md
https://github.com/JJ/CC16-17/blob/master/objetivos/PedroGazquezNavarrete.md
=> Objetivos Semanas 5,6,7 y 8

objetivos/CesarAlbusacJorge.md, proyecto/2.md
Entrega de fichero de objetivos hasta la octava semana
[Objetivos](https://github.com/JJ/CC16-17/blob/master/objetivos/CesarAlbusacJorge.md)
Entrega del hito 2 de Cloud Computing. Provisionamiento de una Máquina Virtual.
También, actualización de objetivos hasta la octava semana.
Se ha cerrado el hito 2.
[Ejercicios del tema 2](https://github.com/cesar2/EjerciciosCloudComputing/blob/master/Temas/tema2.md).
[Documentación](https://cesar2.github.io/Tripbot/).
[Repositorio](https://github.com/cesar2/Tripbot).
[Issue correspondiente al Hito 2](https://github.com/cesar2/Tripbot/issues/3).
=> Subiendo Hito 2 y Objetivos.

proyecto/2.md
Entrega del hito 2 de Cloud Computing, también enlace al repositorio de los ejercicios que se han realizado para la entrega de este hito.
Enlace a los ejercicios realizados: https://github.com/pedrogazquez/EjerciciosCC16-17/blob/master/Tema2GestionDeConfiguraciones/EjerciciosTema2.md
Enlace a la documentación del proyecto: https://pedrogazquez.github.io/FunnyBot/
Enlace a repo del proyecto: https://github.com/pedrogazquez/FunnyBot
=> Arreglando plantilla

objetivos/AlejandroCasadoQuijada.md, proyecto/2.md
[Objetivos](https://github.com/acasadoquijada/CC16-17/blob/master/objetivos/AlejandroCasadoQuijada.md)
Entrega correspondiente al hito 2
[Comprobación de provisionamiento de compañeros](https://github.com/acasadoquijada/MyStudentBot/issues/16)
[Issue 11](https://github.com/acasadoquijada/MyStudentBot/issues/11)
[Issue 13](https://github.com/acasadoquijada/MyStudentBot/issues/13)
[Issue 14](https://github.com/acasadoquijada/MyStudentBot/issues/14)
[Issue 15](https://github.com/acasadoquijada/MyStudentBot/issues/15)
[Milestone 2](https://github.com/acasadoquijada/MyStudentBot/milestone/2)
=> Entrega Hito 2 y objetivos

proyecto/2.md
=> Pulleando que es gerundio corrección.

proyecto/2.md
o
[Borrar lo que no corresponda]
[[ Y lo de arriba también ]]
=> correcion añadida

proyecto/2.md
Corregido fichero con otras correcciones
Añadida correccion de otro compañeros
=> Añadida correccion de otras personas

objetivos/JoseAngelDiazGarcia.md, proyecto/2.md
Y
[Objetivos](https://github.com/joseangeldiazg/CC16-17/blob/commitsJADG/objetivos/JoseAngelDiazGarcia.md)
Entregado los ficheros correspondientes al hito 2 de provisionamiento junto con los ficheros de objetivos. 
Hito 2.
=> Entrega hito 2 y objetivos. 

proyecto/2.md
Editando Campos Tabla de Hito 2
=> Añadiendo campos hito 2

proyecto/2.md
=> Añadiendo correcciones

objetivos/GustavoRivasGervilla.md, proyecto/2.md
y
https://github.com/JJ/CC16-17/blob/master/objetivos/GustavoRivasGervilla.md
Se entrega la documentación relativa al hito 2 (provisionamiento) y se actualiza el fichero de objetivos.
https://github.com/Griger/CC/milestone/3
=> Hito2 y Actualización fichero de objetivos

objetivos/PabloMartín-MorenoRuiz.md
Entrega de los objetivos hasta las semana octava. Se incluye en esta última enlace a los ejercicios del tema 2
=> subiendo objetivos

objetivos/JoseAngelDiazGarcia.md
[Fichero de Objetivos](https://github.com/joseangeldiazg/CC16-17/blob/commitsJADG/objetivos/JoseAngelDiazGarcia.md)
Actualización de los objetivos atrasados de otras semanas y entrega de los ejercicios de temas anteriores.
=> Entrega de ejercicios del tema 2 y 3. Actualización objetivos.

sesiones/9-semana.md
Enlaces al tema sobre configuración en la nube e hito 3 corregidos
=> Corrigiendo enlaces 9 semana

objetivos/JuanPabloGonzalezCasado.md, proyecto/2.md
https://github.com/Pablo126/CC16-17/blob/master/objetivos/JuanPabloGonzalezCasado.md
* [x ] He leído el guión del hito
* [x ] Cumplo los prerrequisitos
* [x ] He actualizado con la última versión del fichero de entrega y
* [x ] He llevado a cabo las actividades correspondientes al objetivo y he entendido para qué sirve.
* [x ] He actualizado con la última versión del fichero de entrega y
Hito 2 realizado con Chef y Ansible.
Ejercicios 1,2,3 y 5 del tema 2.
https://github.com/Pablo126/Cloud-Computing-1617/issues/7#issue-192901162
https://github.com/Pablo126/Cloud-computing-Ejercicios/issues/6
=> Hito2 y ejercicios tema 2

objetivos/MarioOrtegaAguayo.md, proyecto/3.md
Buenas JJ, he añadido la tabla de alumnos para la entrega del hito 3.
=> Añadido fichero para alumnos hito 3

objetivos/JoseLuisFernandezAguilera.md, proyecto/3.md
y
[objetivos](https://github.com/okynos/CC16-17/blob/master/objetivos/JoseLuisFernandezAguilera.md)
Se ha entregado el hito 3 de orquestación y provisionamiento en la nube y automatización del mismo
y se han realizado los ejercicios del tema.
[Hito 3](https://github.com/okynos/ProyectoCC/milestone/4)
[Issue 18](https://github.com/okynos/ProyectoCC/issues/18)
[Issue 19](https://github.com/okynos/ProyectoCC/issues/19)
[Issue 20](https://github.com/okynos/ProyectoCC/issues/20)
[Issue 21](https://github.com/okynos/ProyectoCC/issues/21)
[Issue 22](https://github.com/okynos/ProyectoCC/issues/22)
[Issue 23](https://github.com/okynos/ProyectoCC/issues/23)
[Issue 24](https://github.com/okynos/ProyectoCC/issues/24)
[Issue …
=> Completado fichero de objetivos y entrega del hito 3.

objetivos/ManuelBlancoRienda.md, proyecto/3.md
[Enlace](https://github.com/manuelbr/CC16-17/blob/master/objetivos/ManuelBlancoRienda.md)
Entrega del hito 3 de Manuel Blanco Rienda en el que se ha orquestado máquinas de tres formas diferentes: en local usando un hipervisor de VirtualBox, orquestación de una instancia y provisión de la misma en Trystack y orquestación múltiple (teórica ya que no ha podido ser comprobada en Trystack debido a sus limitaciones) => [Enlace a documentación](https://github.com/manuelbr/Proyecto_CC/blob/master/README.md). También se han realizado todos los ejercicios del tema 3, tanto de la primera como de la segunda parte => [Enlace ejercicios del tema 3 parte …
=> Entrega de hito 3 de Manuel Blanco Rienda

objetivos/FranciscoJavierBolivarLupianez.md, proyecto/3.md
y
Entrega de fichero de objetivos semanas 9 y 10
https://github.com/fblupi/CC16-17/blob/master/objetivos/FranciscoJavierBolivarLupianez.md
Hito 3 y objetivo
https://github.com/fblupi/GEventator/milestone/3
=> Hito 3 y objetivos

objetivos/AythamiEstevezOlivas.md, proyecto/3.md
Corresponde al hito 3 y Entrega de fichero de objetivos 
[Enlace](https://github.com/AythaE/CC16-17/blob/master/objetivos/AythamiEstevezOlivas.md)
Entrega del hito 3 y objetivos hasta la décima semana
[Hito 3](https://github.com/AythaE/DeFesti/milestone/4)
[Issue 11](https://github.com/AythaE/DeFesti/issues/11)
[Issue 12](https://github.com/AythaE/DeFesti/issues/12)
[Issue 13](https://github.com/AythaE/DeFesti/issues/13)
[Ejercicios Orquestación](https://github.com/AythaE/Ejercicios-CC16-17/milestone/4)
[Issue Ej1](https://github.com/AythaE/Ejercicios-CC16-17/issues/20)
[Issue Ej2](https://github.com/AythaE/Ejercicios-CC16-17/issues/21)
[Issue …
=> Añadido hito 3

objetivos/GustavoRivasGervilla.md, proyecto/3.md
y
Entrega de fichero de objetivos
[Fichero objetivos](https://github.com/JJ/CC16-17/blob/master/objetivos/GustavoRivasGervilla.md)
Se añade la línea pertinente para enlazar a la documentación del hito 3 (orquestación) y se actualiza el fichero de objetivos con los objetivos alcanzados hasta la fecha.
[Milestone hito 3](https://github.com/Griger/CC/milestone/4?closed=1)
=> Entrega hito 3 y actualización objetivos.

objetivos/PerezGazquezDaniel.md, proyecto/3.md
https://github.com/NestorsImagination/CC16-17/blob/master/objetivos/PerezGazquezDaniel.md
Hito entregado (aún no corregida la entrega de ningún compañero), objetivos actualizados, ejercicios de Orquestación y Automatizando Cloud entregados.
En https://github.com/NestorsImagination/Sample-Multiplayer-Shooter/issues?q=is%3Aissue+is%3Aclosed, Hito 3, Issues 22, 23 y 24.
=> Hito 3 Daniel Pérez Gázquez

objetivos/JoseAngelDiazGarcia.md, proyecto/3.md
y 
[Objetivos](https://github.com/joseangeldiazg/CC16-17/blob/commitsJADG/objetivos/JoseAngelDiazGarcia.md).
Entregado los ficheros correspondientes al hito 3 de orquestación y actualización de fichero de objetivos. 
Se ha cerrado el hito 3 del proyecto. Este hito podemos encontrarlo en [este enlace](https://github.com/joseangeldiazg/MII-CloudComputing/milestone/2).
=> Entrega de hito 3 y fichero objetivos.

proyecto/3.md
Entrega del hito 3
[Hito 3](https://github.com/jmanday/CRUT/milestone/3)
=> añadido enlace al hito3

objetivos/JoseManuelMoyaBaena.md, proyecto/3.md
o
[Objetivos](https://github.com/jose999/CC16-17/blob/master/objetivos/JoseManuelMoyaBaena.md)
Entrega relacionada con el tema de orquestacion, junto a los ejercicios correspondientes
[Issues Hito 3](https://github.com/jose999/PlayAnywhere/issues/7)
[Issues Ejercicios T3&4](https://github.com/jose999/EjerciciosCC2016/issues/2)
=> Entrega Hito 3

objetivos/PedroGazquezNavarrete.md, proyecto/3.md
https://github.com/JJ/CC16-17/blob/master/objetivos/PedroGazquezNavarrete.md
Entrega del hito 3 y de los objetivos de las semanas anteriores.
Repositorio de ejercicios: https://github.com/pedrogazquez/EjerciciosCC16-17/tree/master/Tema3OrquestacionMaquinasVirtuales
Repositorio app: https://github.com/pedrogazquez/FunnyBot
gh-pages: https://pedrogazquez.github.io/FunnyBot/
=> Subiendo Objetivos y enlace a hito 3

proyecto/3.md
[Objetivos semanas 9,10 y 11](https://github.com/JJ/CC16-17/blob/master/objetivos/PabloMart%C3%ADn-MorenoRuiz.md)
Entrega del hito 3
https://github.com/pmmre/CineForYou/milestone/5
=> Subiendo hito 3

objetivos/PerezGazquezDaniel.md, proyecto/3.md
Hecha corrección de la entrega del Hito 3 de Juan Pablo Porcel Porcel. Actualizado 3.md y objetivos.
Corrección: https://github.com/JPPorcel/Proyecto-Elliot/issues/10
=> Corrección de la entrega del Hito 3 de un compañero

objetivos/MarvinMatiasAgueroTorales.md, proyecto/3.md
y
https://github.com/JJ/CC16-17/blob/master/objetivos/MarvinMatiasAgueroTorales.md
Se orquesta VirtualBox + AWS + TryStack con Vagrant
Issue: https://github.com/mmaguero/MII-CC16-17/issues/6
Hito: https://github.com/mmaguero/MII-CC16-17/milestone/4
Ejercicios: https://github.com/mmaguero/Ejercicios-CC16-17-MII
=> Entregando el objetivos / tabla de proyectos

objetivos/JoseAngelDiazGarcia.md
[Objetivos](https://github.com/joseangeldiazg/CC16-17/blob/master/objetivos/JoseAngelDiazGarcia.md).
Entrega de los objetivos de la última semana y actualización de los ejercicios del tema de orquestación de máquinas virtuales.
=> Actualización de fichero de objetivos.

objetivos/JesusGarciaManday.md, proyecto/4.md
Corresponde al hito 4 + Entrega de fichero de objetivos 
Añadido el fichero 4.md para el hito 4 + entrega del hito 4 +  actualizado el fichero de objetivos
[Hito 4](https://github.com/jmanday/CRUT/milestone/4)
=> Añadido fichero 4.md para el hito 4 +  entrega del hito 4 + entrega fichero objetivos

objetivos/AythamiEstevezOlivas.md, proyecto/4.md
Corresponde al hito 4 y entrega de fichero de objetivos 
[Enlace](https://github.com/AythaE/CC16-17/blob/master/objetivos/AythamiEstevezOlivas.md)
Entrega de ejercicios del tema de contenedores, el hito 4 de docker y actualización del fichero de objetivos
[Hito 4](https://github.com/AythaE/DeFesti/milestone/5)
[Issue 14](https://github.com/AythaE/DeFesti/issues/14)
[Issue 15](https://github.com/AythaE/DeFesti/issues/15)
[Issue 16](https://github.com/AythaE/DeFesti/issues/16)
[Issue 17](https://github.com/AythaE/DeFesti/issues/17)
[Hito Ejercicios contenedores](https://github.com/AythaE/Ejercicios-CC16-17/milestone/5)
[Issue Ejercicio …
=> Añadidos objetivos de semana 11 e hito 4

objetivos/FranciscoJavierBolivarLupianez.md, proyecto/4.md
y
Entrega de fichero de objetivos (semana 11)
[Objetivos](https://github.com/fblupi/CC16-17/blob/master/objetivos/FranciscoJavierBolivarLupianez.md)
Hito 4 (contenedores) y entrega de fichero de objetivos (semana 11)
[Hito 4](https://github.com/fblupi/GEventator/milestone/4)
=> Objetivos undécima semana e hito 4

objetivos/JoseManuelMoyaBaena.md, proyecto/4.md
[Objetivos](https://github.com/jose999/CC16-17/blob/master/objetivos/JoseManuelMoyaBaena.md)
Entrega relacionada con el tema de contenedores, junto a los ejercicios correspondientes
[Issues Hito 4](https://github.com/jose999/PlayAnywhere/issues/8)
[Issues Ejercicios T5](https://github.com/jose999/EjerciciosCC2016/issues/3)
=> Entrega Hito 4 @jose999

objetivos/ManuelBlancoRienda.md, proyecto/4.md
[Enlace a objetivos](https://github.com/manuelbr/CC16-17/blob/master/objetivos/ManuelBlancoRienda.md)
Se entrega el fichero de documentación README, actualizado con un tutorial sobre cómo utilizar docker en local y en azure y el funcionamiento de Dockerfile => [Enlace](https://github.com/manuelbr/Proyecto_CC/blob/master/README.md). También se entregan los ejercicios del tema 4 => [Enlace](https://github.com/manuelbr/ejercicios_CC/tree/master/tema_4). Por último, se adjunta el enlace a la corrección del proyecto de José Luis Fernández Aguilera. => [Enlace](https://github.com/okynos/ProyectoCC/blob/master/contenedores/correccion.md). …
=> Entrega del hito 4 de Manuel Blanco Rienda

objetivos/MarioOrtegaAguayo.md, proyecto/4.md
y
https://github.com/mortega87/CC16-17/blob/master/objetivos/MarioOrtegaAguayo.md
Entrega Hito 4 y actualización de objetivos.
https://github.com/mortega87/ProyectoCC-16-17/issues/18
https://github.com/mortega87/ProyectoCC-16-17/issues/19
https://github.com/mortega87/ProyectoCC-16-17/issues/20
https://github.com/mortega87/ProyectoCC-16-17/issues/21
=> Hito 4 y objetivos actualizados

objetivos/JesusGarciaManday.md, proyecto/4.md
Realizada la corrección del hito 4 a otro compañero + resuelto conflictos del anterior pull request
[Hito 4](https://github.com/jmanday/CRUT/issues/27)
=> añadida la corrección a otro compañero + resuelto conflicto

objetivos/AlejandroCasadoQuijada.md, proyecto/4.md
[Objetivos](https://github.com/acasadoquijada/CC16-17/blob/master/objetivos/AlejandroCasadoQuijada.md)
Entrega correspondiente al Hito 4
[Milestone](https://github.com/acasadoquijada/MyStudentBot/milestone/4)
[Issue 1](https://github.com/acasadoquijada/MyStudentBot/issues/20)
[Issue 2](https://github.com/acasadoquijada/MyStudentBot/issues/21)
[Issue 3](https://github.com/acasadoquijada/MyStudentBot/issues/22)
=> Entrega Hito 4

proyecto/4.md
Hito 4 del proyecto. Se han habilitado contenedores Docker y un repositorio en Dockerhub.
[Issues del hito](https://github.com/joseangeldiazg/MII-CloudComputing/milestone/3?closed=1)
=> Entrega del hito 4.

objetivos/JuanPabloGonzalezCasado.md, proyecto/3.md, proyecto/4.md
Corresponde al hito 3 y 4
y
https://github.com/JJ/CC16-17/blob/master/objetivos/JuanPabloGonzalezCasado.md
Hito 3 y 4, Fichero de objetivos actualizado
https://github.com/Pablo126/Cloud-Computing-1617/milestone/4?closed=1
https://github.com/Pablo126/Cloud-Computing-1617/milestone/5?closed=1
=> Hito3 e Hito4

objetivos/JoseAngelDiazGarcia.md
[Objetivos](https://github.com/joseangeldiazg/CC16-17/blob/master/objetivos/JoseAngelDiazGarcia.md)
Se han actualizado los objetivos cumplidos en las ultimas semanas tales como los relativos a Docker y el hito 4 de la asignatura.
=> Actualización ficheros objetivos últimas semanas.

objetivos/JoseAngelDiazGarcia.md
[Objetivos](https://github.com/joseangeldiazg/CC16-17/blob/master/objetivos/JoseAngelDiazGarcia.md)
Entrega de algunos ejercicios sobre contenedores y actualización de algunos objetivos realizados.
=> Ejercicios contenedores y actualizados objetivos.

objetivos/JuanPabloGonzalezCasado.md
https://github.com/Pablo126/CC16-17/blob/master/objetivos/JuanPabloGonzalezCasado.md
Entregados los ejercicios de los temas 3 y 5.
https://github.com/Pablo126/Cloud-computing-Ejercicios/blob/master/Ejercicios_tema3.md
https://github.com/Pablo126/Cloud-computing-Ejercicios/blob/master/Ejercicios_tema5.md
https://github.com/Pablo126/Cloud-computing-Ejercicios/issues/8
https://github.com/Pablo126/Cloud-computing-Ejercicios/issues/9
=> Ejercicios tema3 y tema5

objetivos/AythamiEstevezOlivas.md, proyecto/5.md
Corresponde al hito 5 y entrega de fichero de objetivos 
[Fichero de objetivos](https://github.com/AythaE/CC16-17/blob/master/objetivos/AythamiEstevezOlivas.md)
Hito 5
[Hito 5](https://github.com/AythaE/DeFesti/milestone/6)
[Issue 18](https://github.com/AythaE/DeFesti/issues/18)
[Issue 19](https://github.com/AythaE/DeFesti/issues/19)
[Issue 20](https://github.com/AythaE/DeFesti/issues/20)
[Issue 21](https://github.com/AythaE/DeFesti/issues/21)
=> Añadido hito final y actualización de objetivos

objetivos/ManuelBlancoRienda.md, proyecto/5.md
[Enlace a fichero de objetivos](https://github.com/manuelbr/CC16-17/blob/master/objetivos/ManuelBlancoRienda.md)
Se entrega el hito final de la asignatura, correspondiente al despliegue automático total de la insfraestructura virtual planteada en la documentación (tres máquinas virtuales diferentes provisionadas, además de la conexión con un servicio externo) del proyecto utilizando en combinación tres tecnologías: Vagrant, Docker, Ansible y Azure. 
https://github.com/manuelbr/Proyecto_CC/milestone/6
https://github.com/manuelbr/Proyecto_CC/issues/69
https://github.com/manuelbr/Proyecto_CC/issues/68
https://github.com/manuelbr/Proyecto_CC/issues/67 …
=> añadido hito final de Manuel Blanco Rienda

objetivos/JoseLuisFernandezAguilera.md, proyecto/5.md
y
[Objetivos](https://github.com/okynos/CC16-17/blob/master/objetivos/JoseLuisFernandezAguilera.md)
Entrega de los objetivos relativos al último hito de la asignatura y el hito 5 en sí.
[Hito 5](https://github.com/okynos/ProyectoCC/milestone/6)
[Issue 36](https://github.com/okynos/ProyectoCC/issues/36)
[Issue 37](https://github.com/okynos/ProyectoCC/issues/37)
[Issue 38](https://github.com/okynos/ProyectoCC/issues/38)
[Issue 39](https://github.com/okynos/ProyectoCC/issues/39)
[Issue 40](https://github.com/okynos/ProyectoCC/issues/40)
[Issue 41](https://github.com/okynos/ProyectoCC/issues/41)
[Issue 42](https://github.com/okynos/ProyectoCC/issues/42)
[Issue 43](https://github.com/okynos/ProyectoCC/issues/43)
[Issue …
=> Añadido fichero de objetivos y entrega del hito 5

objetivos/FranciscoJavierBolivarLupianez.md, proyecto/5.md
y
Entrega de fichero de objetivos de las semanas 12, 13 y 14.
[Objetivos](https://github.com/fblupi/CC16-17/blob/master/objetivos/FranciscoJavierBolivarLupianez.md)
Hito 5 (final) y objetivos (semanas 12, 13 y 14)
[Hito 5](https://github.com/fblupi/GEventator/milestone/5)
=> Objetivos e hito final

proyecto/5.md
Corresponde al hito <5>
[Objetivos](https://github.com/joseangeldiazg/CC16-17/blob/master/objetivos/JoseAngelDiazGarcia.md)
Entregado el último hito de la asignatura donde aunamos diversas tecnologías vistas para el despliegue de la infraestructura virtual. 
[Issues](https://github.com/joseangeldiazg/MII-CloudComputing/milestone/4?closed=1)
=> Entrega del último hito de CC.

objetivos/AlejandroCasadoQuijada.md, proyecto/5.md
[Fichero objetivos](https://github.com/acasadoquijada/CC16-17/blob/master/objetivos/AlejandroCasadoQuijada.md)
Entrega correspondiente al hito 5
[Millestone](https://github.com/acasadoquijada/MyStudentBot/milestone/5)
[Issue 1](https://github.com/acasadoquijada/MyStudentBot/issues/26)
[Issue 2](https://github.com/acasadoquijada/MyStudentBot/issues/25)
[Issue 3](https://github.com/acasadoquijada/MyStudentBot/issues/24)
[Issue 4](https://github.com/acasadoquijada/MyStudentBot/issues/23)
=> Entrega Hito 5

objetivos/MarvinMatiasAgueroTorales.md, proyecto/5.md
https://github.com/JJ/CC16-17/blob/master/objetivos/MarvinMatiasAgueroTorales.md 
Se entrega el despliegue final Vagrant + AWS + Docker + Alpine + Docker Hub + Servicios Externos LaaS y DaaS
https://github.com/mmaguero/MII-CC16-17/issues/8
https://github.com/mmaguero/MII-CC16-17/milestone/6
=> Subiendo hito final Ref #8

objetivos/GustavoRivasGervilla.md, proyecto/5.md
y
Entrega de fichero de objetivos
[Fichero de objetivos](https://github.com/JJ/CC16-17/blob/master/objetivos/GustavoRivasGervilla.md)
Se actualiza el fichero de objetivos con los objetivos completados hasta la fecha y se enlaza a la entrega del último hito.
[Milestone de este último hito](https://github.com/Griger/CC/milestone/6)
=> Actualizando objetivos y entregando último hito.

objetivos/JesusGarciaManday.md, proyecto/5.md
+
Entrega del hito 5 + actualizado el fichero objetivos
[Hito 5](https://github.com/jmanday/CRUT/milestone/5)
=> actualizado fichero objetivos + añadido enlaces para hito 5

objetivos/CesarAlbusacJorge.md, proyecto/5.md
Entrega de fichero de objetivos : 
[Objetivos](https://github.com/JJ/CC16-17/blob/master/objetivos/CesarAlbusacJorge.md)
Entrega del Hito 5 y actualización de objetivos.
Issue cerrado : https://github.com/cesar2/Tripbot/issues/5
=> subiendo hito 5 y objetivos

objetivos/MariaVictoriaSantiagoAlcala.md, proyecto/5.md
Corresponde al hito 5 y entrega de fichero de objetivos 
[Objetivos](https://github.com/JJ/CC16-17/blob/master/objetivos/MariaVictoriaSantiagoAlcala.md)
Fichero de objetivos e hito 5
[Hito 5](https://github.com/STiago/Lecrin_Bot/milestone/6)
[Issue 18](https://github.com/STiago/Lecrin_Bot/issues/18)
[Issue 19](https://github.com/STiago/Lecrin_Bot/issues/19)
[Issue 20](https://github.com/STiago/Lecrin_Bot/issues/20)
[Issue 23](https://github.com/STiago/Lecrin_Bot/issues/23)
=> Entrega de objetivos e Hito 5

objetivos/PedroGazquezNavarrete.md, proyecto/5.md
[Objetivos Pedro Gázquez Navarrete](https://github.com/pedrogazquez/CC16-17/blob/master/objetivos/PedroGazquezNavarrete.md)
Entrego hito 5 junto a los objetivos correspondientes.
=> Objetivos e hito 5

proyecto/5.md
Hito5
Entrega del hito 5.
https://github.com/pmmre/CineForYou/milestone/7
=> Subiendo hito 5

objetivos/JoseManuelMoyaBaena.md, proyecto/5.md
[Objetivos](https://github.com/jose999/CC16-17/blob/master/objetivos/JoseManuelMoyaBaena.md)
Entrega relacionada con el despliegue del sistema
[Issues Hito 4](https://github.com/jose999/PlayAnywhere/issues/10)
=> Entrega Hito despliegue

objetivos/DanielPerezGazquez.md, proyecto/5.md
* Añadida la carpeta "Prototype" que contiene el prototipo funcional y desplegable del sistema: [Prototipo](https://github.com/NestorsImagination/Sample-Multiplayer-Shooter/tree/master/Prototype)
* Actualizados ficheros de objetivos y 5.md
* Actualizada la documentación: [Página completa](https://nestorsimagination.github.io/Sample-Multiplayer-Shooter/) [Nueva documentación](https://github.com/NestorsImagination/Sample-Multiplayer-Shooter/blob/master/Prototype/README.md)
* Hito cerrado: [Hito 5](https://github.com/NestorsImagination/Sample-Multiplayer-Shooter/milestone/6?closed=1)
_Nota: Si lo desea, dígamelo por Telegram y puedo abrir el servidor AWS para que pruebe su funcionamiento y darle el enlace_
=> Entrega Hito 5 Daniel Pérez Gázquez

objetivos/JuanPabloGonzalezCasado.md, proyecto/5.md
y
https://github.com/Pablo126/Cloud-Computing-1617/tree/master/despliegue
Hito 5 y objetivos
https://github.com/Pablo126/Cloud-Computing-1617/tree/master/despliegue
https://github.com/Pablo126/Cloud-Computing-1617/issues/12
https://github.com/Pablo126/Cloud-Computing-1617
https://github.com/Pablo126/Cloud-Computing-1617/blob/master/despliegue/README.md
=> Hito 5 y objetivos

proyecto/5.md
Entrega de fichero de objetivos : 
[Objetivos](https://github.com/JJ/CC16-17/blob/master/objetivos/CesarAlbusacJorge.md)
Entrega del Hito 5 y actualización de objetivos.
Issue cerrado : https://github.com/cesar2/Tripbot/issues/5
=> poniendo enlaces
